Ajout du mode multi-joueur avec des sockets
bastiengrignon/Shanghai pull request #20
Opened 2020-11-23 17:38 UTC by LucasPerrault

- Ajout de la connexion par socket avec le serveur.
- Ajout de la connexion aux différents types de room (public, privée ou créé par soi même).
- Ajout de la salle d'attente en attendant d'autres joueurs
- Gestion de la déconnexion par n'importe quel moyen.

2020-11-23 20:40 UTC, bastiengrignon requested changes

2020-11-23 20:40 UTC, bastiengrignon commented on app/src/main/java/com/grignon/shanghai/OnlineRoomFragment.java
> +        TextView roomCodeTextView = view.findViewById(R.id.roomCodeText);
Ici c'est que mon avis mais je trouve ça mieux de mettre tous les `findViewById` au début à la suite et après tu utilise les variables au fil du code
Mais c'est que mon point de vue 😉

2020-11-23 20:40 UTC, bastiengrignon commented on app/src/main/java/com/grignon/shanghai/OnlineRoomFragment.java
> +        if (room.getPlayers().size() < 2) {
Utilise une variable constante ici 
Tu peux la mettre dans la classe `Constant` si tu veux avec un nom explicite

2020-11-23 20:40 UTC, bastiengrignon commented on app/src/main/java/com/grignon/shanghai/OnlineRoomFragment.java
> +    };
Pas refactoré ici non plus 
Le copié-collé c'est pas bien 👀

2020-11-23 20:40 UTC, bastiengrignon commented on app/src/main/java/com/grignon/shanghai/OnlineRoomFragment.java
> +            getActivity().runOnUiThread(new Runnable() {
Utilse require pour éviter des NullPointerException 
```suggestion
            requireActivity().runOnUiThread(new Runnable() {
```

2020-11-23 20:40 UTC, bastiengrignon commented on app/src/main/java/com/grignon/shanghai/OnlineRoomFragment.java
> +            getActivity().runOnUiThread(new Runnable() {
```suggestion
            requireActivity().runOnUiThread(new Runnable() {
```

2020-11-23 20:40 UTC, bastiengrignon commented on app/src/main/java/com/grignon/shanghai/OnlineRoomPlayersAdapter.java
> +import android.graphics.Color;
Le Color est pas utilisé tu peux enlever le import

2020-11-23 20:40 UTC, bastiengrignon commented on app/src/main/java/com/grignon/shanghai/OnlineRoomPlayersAdapter.java
> +    @Override
```suggestion
    @NonNull
    @Override
```

2020-11-23 20:40 UTC, bastiengrignon commented on app/src/main/java/com/grignon/shanghai/OnlineRoomPlayersAdapter.java
> +    public ViewHolder onCreateViewHolder(ViewGroup parent, int viewType) {
```suggestion
    public ViewHolder onCreateViewHolder(@NonNull ViewGroup parent, int viewType) {
```

2020-11-23 20:40 UTC, bastiengrignon commented on app/src/main/java/com/grignon/shanghai/OnlineRoomPlayersAdapter.java
> +    public class ViewHolder extends RecyclerView.ViewHolder {
Ta classe ViewHolder peut être static

2020-11-23 20:40 UTC, bastiengrignon commented on app/src/main/java/com/grignon/shanghai/entity/Player.java
> +    private String nickname;
C'est que des **get** donc tu peut les mettre `final`
```suggestion
    private final String socketId;
    private final String nickname;
```

2020-11-23 20:40 UTC, bastiengrignon commented on app/src/main/java/com/grignon/shanghai/entity/Room.java
> +    private List<Player> players;
Tous tes paramètres peuvent être final ici aussi 
```suggestion
    private final String name;
    private final String code;
    private final Integer type;
    private final Player admin;
    private final List<Player> players;
```

2020-11-23 20:40 UTC, bastiengrignon commented on app/src/main/java/com/grignon/shanghai/socket/ShanghaiApplication.java
> +    private Socket mSocket;
final ici aussi 😉 
```suggestion
    private final Socket mSocket;
```

2020-11-23 20:40 UTC, bastiengrignon commented on app/src/main/java/com/grignon/shanghai/socket/services/SocketConnectionService.java
> +        /* Socket listenners initialization */
C'est un `n` en trop mais bon c'est de la typo donc on s'en fou si tu veux 😉

2020-11-23 20:40 UTC, bastiengrignon commented on app/src/main/java/com/grignon/shanghai/socket/services/SocketRoomConnectionService.java
> +        ShanghaiApplication app = (ShanghaiApplication) fragment.getActivity().getApplication();
```suggestion
        ShanghaiApplication app = (ShanghaiApplication) fragment.requireActivity().getApplication();
```

2020-11-23 20:40 UTC, bastiengrignon commented on app/src/main/java/com/grignon/shanghai/socket/services/SocketRoomConnectionService.java
> +        /* Socket listenners initialization */
Listener ça prend qu'un seul **n** ^^

2020-11-23 20:40 UTC, bastiengrignon commented on app/src/main/java/com/grignon/shanghai/socket/services/SocketRoomService.java
> +        /* Socket listenners initialization */
Toujours de **n** x)

2020-11-23 20:40 UTC, bastiengrignon commented on app/src/main/res/layout-land/player_recycler_row_layout.xml
> +        android:gravity="left"
Utilise `start` à la place de `left` c'est mieux

2020-11-23 20:40 UTC, bastiengrignon commented on app/src/main/res/layout/fragment_online_room_connection.xml
> +                android:layout_marginLeft="10dp"
Pour tous les `margin` et `padding` utilise **start** et **end** à la place c'est mieux 
Ligne 25, 35, 66, 125

2020-11-23 20:40 UTC, bastiengrignon commented on app/src/main/res/values-fr-rFR/strings.xml
> +    <string name="error_room_code_not_found">Désolé nous n avons pas trouvé cette salle.</string>
Il y a pas d'apostrophe
```suggestion
    <string name="error_room_code_not_found">Désolé nous n'avons pas trouvé cette salle.</string>
```

2020-11-23 20:40 UTC, bastiengrignon commented on app/src/main/res/values-fr-rFR/strings.xml
> +    <string name="error_socket_nick_name_empty">Désolé mais le serveur n a pas reçu votre surnom. Veuillez réessayer.</string>
Il y a pas d'apostrophe
```suggestion
    <string name="error_socket_nick_name_empty">Désolé mais le serveur n'a pas reçu votre surnom. Veuillez réessayer.</string>
```

2020-11-23 20:40 UTC, bastiengrignon commented on app/src/main/res/values/strings.xml
> +    <string name="error_room_code_not_found">Sorry but we didnt find this code room.</string>
```suggestion
    <string name="error_room_code_not_found">Sorry but we didn\'t find this code room.</string>
```

2020-11-23 20:42 UTC, bastiengrignon commented
Je serais chaud pour que tu mettes tout tes **OnlineRoom** dans un package un peu comme ta fais pour les `socket`

2020-11-24 07:51 UTC, LucasPerrault commented on app/src/main/AndroidManifest.xml
> +        android:usesCleartextTraffic="true"
Oui c'est ça. Sans ça, ça ne fonctionnera pas en local. Le mieux avant de l'enlever serait de mettre en ligne la version serveur. Soit on créé une issue pour penser à l'enlever, soit je l'enlève maintenant et cette branche attend. C'est comme tu veux dit moi ;)

2020-11-24 08:56 UTC, LucasPerrault commented on app/src/main/java/com/grignon/shanghai/OnlineRoomConnectionFragment.java
> +        /* Ne pas se déconnecter du serveur si pas connecté */
Si, si c'est bien géré. Lorsque le serveur est pas connecté, il y a juste un toast qui s'affiche. C'est tout.. :)

2020-11-24 08:59 UTC, bastiengrignon commented on app/src/main/AndroidManifest.xml
> +        android:usesCleartextTraffic="true"
Oui on peut créer une issu c'est le mieux je pense on sait jamais

2020-11-24 10:01 UTC, bastiengrignon reviewed
Il manque un `isEmpty()` t'n a changé 1 mais il y en avait 2

2020-11-24 10:07 UTC, bastiengrignon commented on app/src/main/java/com/grignon/shanghai/onlineroom/fragments/OnlineRoomConnectionFragment.java
> +        if (privateGameId.getText().length() == 0) {
`isEmpty()` ici

2020-11-24 10:07 UTC, bastiengrignon commented on app/src/main/java/com/grignon/shanghai/onlineroom/fragments/OnlineRoomFragment.java
> +        String roomTitle = getResources().getString(R.string.welcome_room) + " " + room.getName();
Tu peux utiliser les paramètres de string ici aussi

2020-11-24 10:34 UTC, bastiengrignon approved these changes

2020-11-24 11:20 UTC, merged